### ISSUE TITLE
Deciding on a journal

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/An-open-reproducible-framework-for-the-study-of-the-iterated-prisoners-dilemma#13]
This could give us some guidance: http://www.software.ac.uk/resources/guides/which-journals-should-i-publish-my-software

Any suggestions? I think everyone's constraints are the same:
- Open
- On arxiv also

**Comment by meatballs** [comment]
I like the look of http://openresearchsoftware.metajnl.com/

**Comment by langner** [comment]
You might also consider publishing each major release of the code on Figshare or Zenodo, so its citable  by DOI.

**Comment by drvinceknight** [comment]
That's done @langner: https://zenodo.org/record/45187#.VrhJUVSLRhE

(There's a badge on the README.)

**Comment by drvinceknight** [comment]
> I like the look of http://openresearchsoftware.metajnl.com/

:+1: Looks great to me.

**Comment by langner** [comment]
Ah yes. Way cool.

**Comment by drvinceknight** [comment]
There's a couple of things about that journal that need to be thought about (fees):

http://openresearchsoftware.metajnl.com/about/submissions/

**Comment by drvinceknight** [comment]
> There's a couple of things about that journal that need to be thought about (fees):

To be clear, if we did go anywhere with fees, I would be able to cover them through CU.

**Comment by drvinceknight** [comment]
It looks like the JORS submission policy has changed slightly since we last looked. They now offer a LaTeX template. Going with them :)

**Comment by drvinceknight** [comment]
Actually, looking at the template. It's mildly restrictive, going to drop the editor a line.

**Comment by drvinceknight** [comment]
This is now on the JORS branch: https://github.com/Axelrod-Python/An-open-reproducible-framework-for-the-study-of-the-iterated-prisoners-dilemma/tree/jors

Waiting to hear back from editor and also to get author info OK'd.

**Comment by drvinceknight** [comment]
This is another option: http://www.springer.com/economics/economic+theory/journal/182

(CU could cover the open access fees: I'd rather not go with a closed open access solution like this.)

**Comment by meatballs** [comment]
> closed open access solution.....

I don't understand what that means - but I'm happy for it to be published wherever you think best!

**Comment by drvinceknight** [comment]
This: http://www.worldscientific.com/worldscinet/igtr is also an option and they have this as their OA policy: http://www.worldscientific.com/page/open

**Comment by meatballs** [comment]
> Actually, looking at the template. It's mildly restrictive, going to drop the editor a line.

What's the restriction?

**Comment by drvinceknight** [comment]
> I don't understand what that means - but I'm happy for it to be published wherever you think best!

<rant>
It's the ridiculous situation where:
- Academics do the research (paid for by the tax payer);
- They submit it to a journal;
- Everyone complains that papers should be viewable by all;
- Journals kindly offer to for a small fee (usually around £1500) make the article available to all;
- ~~Academics~~ Tax payers pay this fee

In essence there's open access and open access: one of them is real the other is just were publishers get paid twice (and academics still do all the work). 

</rant>

**Comment by meatballs** [comment]
> This: http://www.worldscientific.com/worldscinet/igtr is also an option and they have this as their OA policy: http://www.worldscientific.com/page/open

The policy page lists three 'Full Open Access Journals', but igtr isn't one of them.

**Comment by meatballs** [comment]
> It's the ridiculous situation where: .....

Ah! I see. That stinks and I'd rather go nowhere near it!

**Comment by drvinceknight** [comment]
> What's the restriction?

They want quite a strict structure: here is an example http://openresearchsoftware.metajnl.com/articles/10.5334/jors.104/
- Overview
- Availability
- Reuse potential

We could write an article in that format but it would read as more of a "brochure" than the current paper. There's nothing stopping us writing that one as well.

I've asked if something a bit different would be of interest to the journal.

**Comment by drvinceknight** [comment]
> The policy page lists three 'Full Open Access Journals', but igtr isn't one of them.

Missed that.

**Comment by drvinceknight** [comment]
> The policy page lists three 'Full Open Access Journals', but igtr isn't one of them.

Yup: http://www.worldscientific.com/page/igtr/submission-guidelines says: "Once the paper is accepted, authors are assumed to cede copyrights of the paper over to World Scientific Publishing Co.". That ones gone.

**Comment by meatballs** [comment]
IGTR: None of the articles in there have the open access icon next to them

**Comment by drvinceknight** [comment]
I like the look of http://www.springer.com/business+%26+management/operations+research/journal/10287 (gambit papers have gone there) but there is a fee for open access: http://www.springer.com/gp/open-access/springer-open-choice

**Comment by drvinceknight** [comment]
I really like the look of http://www.hindawi.com/journals/gt/

**Comment by drvinceknight** [comment]
This is another option: http://www.mdpi.com/journal/games/apc

**Comment by meatballs** [comment]
> I really like the look of http://www.hindawi.com/journals/gt/

$195 seems like a more reasonable publishing fee!

**Comment by meatballs** [comment]
> This is another option: http://www.mdpi.com/journal/games/apc

500 CHF is slightly more but still better than > $1000!

**Comment by drvinceknight** [comment]
> 500 CHF is slightly more but still better than > $1000!

Apparently: £362

**Comment by drvinceknight** [comment]
Could also go for PLOS ONE although that has a high cost again: $1,495 USD

http://journals.plos.org/plosone/s/publication-fees

This would/could be covered by CU.

**Comment by meatballs** [comment]
I'm out of my depth here - if it's open access, I'm happy. Go with whatever might suit you best.

**Comment by drvinceknight** [comment]
> I'm out of my depth here - if it's open access, I'm happy. Go with whatever might suit you best.

I'm happy to make a call at some point, will keep writing down things here in case anyone has any objections.

**Comment by drvinceknight** [comment]
I've just been speaking to the editor of JORS who clarified the required structure. We could add the availability and reuse sections and then it would be fine. They did however also suggest: http://toms.acm.org/ which looks good too.

**Comment by drvinceknight** [comment]
Have decided to go with JORS. Setting the jors branch of this repo to the default one. Going to spend some time reading over it this pm but basically there now.

**Comment by langner** [comment]
Afterthought: perhaps we could just publish on arxiv and choose a journal later?

**Comment by drvinceknight** [comment]
Hey Karol, was going to do both today: put it on arxiv and submit to JORS. If you think there's a particular reason to hold fire with the journal let me know :)

**Comment by meatballs** [comment]
> Afterthought: perhaps we could just publish on arxiv and choose a journal later?

If it was good enough for Grigori Perelman......

**Comment by drvinceknight** [comment]
> If it was good enough for Grigori Perelman......

Haha true. I guess the only reason to do so would be because we want to think about the journal a bit more. I'm happy with JORS: any reservations? (Re-opening the issue)

**Comment by meatballs** [comment]
> I'm happy with JORS: any reservations? (Re-opening the issue)

None whatsoever.

**Comment by drvinceknight** [comment]
I'll hold fire till tomorrow @langner :+1:

**Comment by drvinceknight** [comment]
Paper has been submitted. :) :+1:

**Comment by langner** [comment]
I was expecting some of the parts to be more fleshed out, but it's all good.
