### ISSUE TITLE
Comments on the latest draft

### ISSUE THREAD

**Issue by marcharper** [Axelrod-Python/An-open-reproducible-framework-for-the-study-of-the-iterated-prisoners-dilemma#16]
"These works investigate particular evolutionary contexts within which cooperation can emerge as stable.
Often these works consider direct opposition to another strategy and disregard
the population dynamics, for example in \cite{Lee2015} a machine learning
algorithm outperforms a strategy found in \cite{Press2012}."

I would say instead perhaps:

"These works investigate particular evolutionary contexts within which cooperation can evolve and persist. This can be in the context of direct interactions between strategies or population dynamics for populations of many players using a variety of strategies, which can lead to very different results. For example, in \cite{Lee2015} a machine learning algorithm in a population context outperforms strategies described in \cite{Press2012} and \cite{Stewart2012} that are claimed to dominate any evolutionary opponent in head-to-head interactions."

Here I think there is a word missing:

"Due to the open nature of the library the number of strategies included has
grown at a fast pace, as can be seen in Figure~\ref{fig:number_of_strategies_against_date}. Despite this, due to previous research being done in an irreproducible _manner_ , with for example no
source code, and/or vaguely described strategies, not all previous tournaments
are yet to be reproduced. In fact, some of the early tournaments might be
impossible to reproduce as the source code is forever lost, this library aims to
prevent this from happening again in the future." [Is the last sentence grammatically correct?]

**Comment by drvinceknight** [comment]
Thanks for taking a look @marcharper :)

Have added those two things here: 99786ca22c6a0ad5465726043bc824cd3cfb5a0c

> "In fact, some of the early tournaments might be
> impossible to reproduce as the source code is forever lost, this library aims to
> prevent this from happening again in the future." [Is the last sentence grammatically correct?]

I've read it a couple of times and seems fine to me. Any thoughts @meatballs?

**Comment by drvinceknight** [comment]
@meatballs said:

> The comma after lost should be either a period or semi colon

Just noting this so I keep track (going to make these tweaks shortly).

**Comment by drvinceknight** [comment]
All addressed by 243c8a2eca5fb313a990b7901178152c8781c311
