### ISSUE TITLE
Discuss the topic of the paper

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/An-open-reproducible-framework-for-the-study-of-the-iterated-prisoners-dilemma#2]
No big rush with this from my point of view but just putting it up as a place to talk about :)

**Comment by langner** [comment]
We could... or let it grow organically.

**Comment by drvinceknight** [comment]
Yup: sounds good to me.

**Comment by langner** [comment]
Let's try to poke around and see if any ideas come up, beyond describing the library itself. First stub: #3

**Comment by drvinceknight** [comment]
I'd like to make a suggesting along the lines of 'beyond describing the library itself'.

@meatballs has suggested 3 objectives for the library/project https://github.com/Axelrod-Python/Axelrod/issues/251

I think the paper could be along those lines. I would suggest that this (first) paper does not analyse anything or indeed try to do anything too novel. It should be an exposition of the library/project (in the same way that some blog posts have already done) targeted at an academic/game theoretic audience.

# An open reproducible framework for the study of the iterated prisoner's dilemma

## Intro - lit review

## Reproducing previous tournament that do not have open documented code
- Include for example the tournament that @marcharper recently reproduced on https://github.com/Axelrod-Python/Axelrod/pull/250
- Original etc..

## New tournaments (for example the memory one tournament that Marc suggested)
- Example of code

## New strategies
- Discuss background of some of the people submitting (for example one of them is by a 15 year old high school student, another by an undergraduate with no prior knowledge of code who did it in an afternoon etc...)

## Conclude

Does anyone have any thoughts? (If everyone's cool I'd suggest we change the name of the repo to the title of the paper, and perhaps plan first steps, I think it makes sense to carve up issues and assign - I am happy to pick up a fair few).

**Comment by meatballs** [comment]
Having never contributed to an academic paper in my life, I'm happy to be guided by those in the know! All sounds good to me and, having something stubbed out gives me a far better chance of making a contribution.

**Comment by drvinceknight** [comment]
I've changed the name of this repository and dc1c430ce39f4404cc3493965afd1cc62cc31709 makes adds to the original stub based on my suggestion above.
