### ISSUE TITLE
Write the introduction.

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/An-open-reproducible-framework-for-the-study-of-the-iterated-prisoners-dilemma#5]
I'm happy to take this on (based on my suggested structure - please do say if anyone would rather a different structure/approach...). I realistically won't get to it before 2015-08-21.

**Comment by langner** [comment]
Go for it.

**Comment by drvinceknight** [comment]
I've just pushed a basic first draft of the introduction: edea95cff34e55c61a81c258367dc9f9e0290fe1 followed by f1d5e9f9eff157dfb7d54109586ca1339099b490

It's disjointed and not as smooth as I'd like it but I'm only ever getting 30 minutes here and there in between meetings and teaching so probably best for someone else to take a look.

Some comments:
- I've also reorganized the repo slightly (3 directories: `tex`, `img` and `scripts`).
- Bibs are not tidy, have left them just appearing generically based on my manager output, I suggest we fix those at a later stage (depending on the journal we go for it'll be easy to use template etc...).

I know I worked directly on master but suggest from now we each work on branches and discuss on PRs?

@marcharper said he'd take a look at intro and I'm sure he could/add improve the lit review so perhaps it's best for him to work on next?

**Comment by marcharper** [comment]
I made some edits on a [new branch](https://github.com/Axelrod-Python/An-open-reproducible-framework-for-the-study-of-the-iterated-prisoners-dilemma/tree/marc).

**Comment by drvinceknight** [comment]
Awesome, I'm more or less out tomorrow but will check through on Thursday!
:)

**Comment by drvinceknight** [comment]
Have opened a PR to chat but basically looks great to me. #8
